repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [--line-length=79, --skip=docs/source/conf.py, --diff]

  - repo: https://github.com/ikamensh/flynt
    rev: '0.76'
    hooks:
      - id: flynt

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus, --keep-runtime-typing]

  - repo: https://github.com/pycqa/pylint
    rev: v3.3.6
    hooks:
      - id: pylint
        args: [--disable=import-error]
        exclude: (^docs/|^scripts)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-click
          - types-pytz
          - types-pyyaml
          - types-requests
          - types-setuptools
          - polars
        args: [pandera, tests, scripts]
        exclude: (^docs/|^tests/mypy/modules/)
        pass_filenames: false
        require_serial: true
        verbose: true
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
exclude: (^asv_bench|setup.py|requirements-dev.txt)

